using System;
using System.Collections.Generic;
using System.Linq;
using Avalonia.Media;
using EmuSen.LunaP.Controls;

namespace EmuSen.LunaP.Tests
{
    // The defaults the drawn controls of §98 to §101 name in their summaries, checked like every other - see docs/LunaP.md §98.6.
    public partial class DocumentedDefaultTests
    {
        private static (string Member, string Claim, Func<object?> Read)[] Claims => CoreClaims.Concat(DrawnClaims).ToArray();

        private static Dictionary<string, object?> Values => CoreValues.Concat(DrawnValues).ToDictionary(p => p.Key, p => p.Value);

        private static readonly (string Member, string Claim, Func<object?> Read)[] DrawnClaims =
        {
            ("P:EmuSen.LunaP.Controls.BadgeStrip.Direction", "Horizontal by default", () => new BadgeStrip().Direction),
            ("P:EmuSen.LunaP.Controls.BadgeStrip.Lines", "1 by default", () => new BadgeStrip().Lines),
            ("P:EmuSen.LunaP.Controls.BadgeStrip.ItemsPerLine", "4 by default", () => new BadgeStrip().ItemsPerLine),
            ("P:EmuSen.LunaP.Controls.BadgeStrip.ContentHorizontalAlignment", "Left by default", () => new BadgeStrip().ContentHorizontalAlignment),
            ("P:EmuSen.LunaP.Controls.BadgeStrip.ContentVerticalAlignment", "Top by default", () => new BadgeStrip().ContentVerticalAlignment),
            ("P:EmuSen.LunaP.Controls.BadgeStrip.Tint", "White by default", () => new BadgeStrip().Tint),
            ("P:EmuSen.LunaP.Controls.ClockLabel.Format", "\"HH:mm\" by default", () => new ClockLabel().Format),
            ("P:EmuSen.LunaP.Controls.ClockLabel.Live", "False by default", () => new ClockLabel().Live),
            ("P:EmuSen.LunaP.Controls.DeviceStatusBar.Indicators", "All by default", () => new DeviceStatusBar().Indicators),
            ("P:EmuSen.LunaP.Controls.DeviceStatusBar.IconHeight", "16 by default", () => new DeviceStatusBar().IconHeight),
            ("P:EmuSen.LunaP.Controls.DeviceStatusBar.TextScale", "1 by default", () => new DeviceStatusBar().TextScale),
            ("P:EmuSen.LunaP.Controls.DeviceStatusBar.Color", "the palette's text colour by default", () => new DeviceStatusBar().Color),
            ("P:EmuSen.LunaP.Controls.DeviceStatusBar.BackgroundColor", "Transparent by default", () => new DeviceStatusBar().BackgroundColor),
            ("P:EmuSen.LunaP.Controls.DeviceStatusBar.BackgroundCornerRadius", "0 by default", () => new DeviceStatusBar().BackgroundCornerRadius),
            ("P:EmuSen.LunaP.Controls.DeviceStatusBar.EntrySpacing", "6 by default", () => new DeviceStatusBar().EntrySpacing),
            ("P:EmuSen.LunaP.Controls.FittedImage.Fit", "Contain by default", () => new FittedImage().Fit),
            ("P:EmuSen.LunaP.Controls.FittedImage.CropPosition", "(0.5, 0.5), the centre, by default", () => new FittedImage().CropPosition),
            ("P:EmuSen.LunaP.Controls.FittedImage.TileHorizontalAlignment", "Left by default", () => new FittedImage().TileHorizontalAlignment),
            ("P:EmuSen.LunaP.Controls.FittedImage.TileVerticalAlignment", "Top by default", () => new FittedImage().TileVerticalAlignment),
            ("P:EmuSen.LunaP.Controls.FittedImage.Tint", "White, no change, by default", () => new FittedImage().Tint),
            ("P:EmuSen.LunaP.Controls.FittedImage.TintEnd", "Null by default", () => new FittedImage().TintEnd),
            ("P:EmuSen.LunaP.Controls.FittedImage.TintDirection", "Horizontal by default", () => new FittedImage().TintDirection),
            ("P:EmuSen.LunaP.Controls.FittedImage.Saturation", "1 by default", () => new FittedImage().Saturation),
            ("P:EmuSen.LunaP.Controls.FittedImage.CornerRadius", "0 by default", () => new FittedImage().CornerRadius),
            ("P:EmuSen.LunaP.Controls.FittedImage.Interpolation", "HighQuality, linear, by default", () => new FittedImage().Interpolation),
            ("P:EmuSen.LunaP.Controls.FontText.FontSize", "16 by default", () => new FontText().FontSize),
            ("P:EmuSen.LunaP.Controls.FontText.Foreground", "the palette's text colour by default", () => new FontText().Foreground),
            ("P:EmuSen.LunaP.Controls.FontText.TextAlignment", "Left by default", () => new FontText().TextAlignment),
            ("P:EmuSen.LunaP.Controls.FontText.TextVerticalAlignment", "Top by default", () => new FontText().TextVerticalAlignment),
            ("P:EmuSen.LunaP.Controls.FontText.LineSpacing", "1.2 by default", () => new FontText().LineSpacing),
            ("P:EmuSen.LunaP.Controls.FontText.LetterCase", "None by default", () => new FontText().LetterCase),
            ("P:EmuSen.LunaP.Controls.FontText.Wrap", "True by default", () => new FontText().Wrap),
            ("P:EmuSen.LunaP.Controls.FontText.Ellipsis", "a horizontal ellipsis by default", () => new FontText().Ellipsis),
            ("P:EmuSen.LunaP.Controls.FontText.Background", "None by default", () => new FontText().Background),
            ("P:EmuSen.LunaP.Controls.FontText.BackgroundCornerRadius", "0 by default", () => new FontText().BackgroundCornerRadius),
            ("P:EmuSen.LunaP.Controls.HintBar.FontSize", "16 by default", () => new HintBar().FontSize),
            ("P:EmuSen.LunaP.Controls.HintBar.EntryScale", "1 by default", () => new HintBar().EntryScale),
            ("P:EmuSen.LunaP.Controls.HintBar.IconColor", "the palette's text colour by default", () => new HintBar().IconColor),
            ("P:EmuSen.LunaP.Controls.HintBar.TextColor", "the palette's text colour by default", () => new HintBar().TextColor),
            ("P:EmuSen.LunaP.Controls.HintBar.BackgroundColor", "Transparent by default", () => new HintBar().BackgroundColor),
            ("P:EmuSen.LunaP.Controls.HintBar.BackgroundCornerRadius", "0 by default", () => new HintBar().BackgroundCornerRadius),
            ("P:EmuSen.LunaP.Controls.HintBar.EntrySpacing", "16 by default", () => new HintBar().EntrySpacing),
            ("P:EmuSen.LunaP.Controls.HintBar.IconTextSpacing", "6 by default", () => new HintBar().IconTextSpacing),
            ("P:EmuSen.LunaP.Controls.HintBar.LetterCase", "None by default", () => new HintBar().LetterCase),
            ("P:EmuSen.LunaP.Controls.ImageCarousel.Orientation", "Horizontal by default", () => new ImageCarousel().Orientation),
            ("P:EmuSen.LunaP.Controls.ImageCarousel.MaxItemCount", "3 by default", () => new ImageCarousel().MaxItemCount),
            ("P:EmuSen.LunaP.Controls.ImageCarousel.ItemScale", "1.2 by default", () => new ImageCarousel().ItemScale),
            ("P:EmuSen.LunaP.Controls.ImageCarousel.Wraps", "True by default", () => new ImageCarousel().Wraps),
            ("P:EmuSen.LunaP.Controls.ImageCarousel.UnfocusedItemOpacity", "0.5 by default", () => new ImageCarousel().UnfocusedItemOpacity),
            ("P:EmuSen.LunaP.Controls.ImageCarousel.UnfocusedItemSaturation", "1 by default", () => new ImageCarousel().UnfocusedItemSaturation),
            ("P:EmuSen.LunaP.Controls.ImageCarousel.UnfocusedItemDimming", "1 by default", () => new ImageCarousel().UnfocusedItemDimming),
            ("P:EmuSen.LunaP.Controls.ImageCarousel.ImageTint", "white by default", () => new ImageCarousel().ImageTint),
            ("P:EmuSen.LunaP.Controls.ImageCarousel.ImageSaturation", "1 by default", () => new ImageCarousel().ImageSaturation),
            ("P:EmuSen.LunaP.Controls.ImageCarousel.ImageFit", "Contain by default", () => new ImageCarousel().ImageFit),
            ("P:EmuSen.LunaP.Controls.ImageCarousel.ItemVerticalAlignment", "Center by default", () => new ImageCarousel().ItemVerticalAlignment),
            ("P:EmuSen.LunaP.Controls.ImageCarousel.ItemHorizontalAlignment", "Center by default", () => new ImageCarousel().ItemHorizontalAlignment),
            ("P:EmuSen.LunaP.Controls.ImageCarousel.Background", "None by default", () => new ImageCarousel().Background),
            ("P:EmuSen.LunaP.Controls.ImageCarousel.FontSize", "24 by default", () => new ImageCarousel().FontSize),
            ("P:EmuSen.LunaP.Controls.ImageCarousel.TextColor", "the palette's text colour by default", () => new ImageCarousel().TextColor),
            ("P:EmuSen.LunaP.Controls.ImageCarousel.TextBackground", "Transparent by default", () => new ImageCarousel().TextBackground),
            ("P:EmuSen.LunaP.Controls.ImageCarousel.LetterCase", "None by default", () => new ImageCarousel().LetterCase),
            ("F:EmuSen.LunaP.Controls.NormalizedCanvas.PositionProperty", "(0, 0) by default", () => new Avalonia.Controls.Border().GetValue(NormalizedCanvas.PositionProperty)),
            ("F:EmuSen.LunaP.Controls.NormalizedCanvas.SizeProperty", "(0, 0) by default", () => new Avalonia.Controls.Border().GetValue(NormalizedCanvas.SizeProperty)),
            ("F:EmuSen.LunaP.Controls.NormalizedCanvas.MaxSizeProperty", "(0, 0), no limit, by default", () => new Avalonia.Controls.Border().GetValue(NormalizedCanvas.MaxSizeProperty)),
            ("F:EmuSen.LunaP.Controls.NormalizedCanvas.OriginProperty", "(0, 0), the top left, by default", () => new Avalonia.Controls.Border().GetValue(NormalizedCanvas.OriginProperty)),
            ("F:EmuSen.LunaP.Controls.NormalizedCanvas.RotationProperty", "0 by default", () => new Avalonia.Controls.Border().GetValue(NormalizedCanvas.RotationProperty)),
            ("F:EmuSen.LunaP.Controls.NormalizedCanvas.RotationOriginProperty", "(0.5, 0.5), the centre, by default", () => new Avalonia.Controls.Border().GetValue(NormalizedCanvas.RotationOriginProperty)),
            ("F:EmuSen.LunaP.Controls.NormalizedCanvas.DepthProperty", "0 by default", () => new Avalonia.Controls.Border().GetValue(NormalizedCanvas.DepthProperty)),
            ("P:EmuSen.LunaP.Controls.StarRating.StarCount", "5 by default", () => new StarRating().StarCount),
            ("P:EmuSen.LunaP.Controls.StarRating.Tint", "White by default", () => new StarRating().Tint),
            ("P:EmuSen.LunaP.Controls.TextRowList.FontSize", "16 by default", () => new TextRowList().FontSize),
            ("P:EmuSen.LunaP.Controls.TextRowList.LineSpacing", "1.5 by default", () => new TextRowList().LineSpacing),
            ("P:EmuSen.LunaP.Controls.TextRowList.PrimaryColor", "the palette's text colour by default", () => new TextRowList().PrimaryColor),
            ("P:EmuSen.LunaP.Controls.TextRowList.SecondaryColor", "the palette's muted colour by default", () => new TextRowList().SecondaryColor),
            ("P:EmuSen.LunaP.Controls.TextRowList.SelectedColor", "the palette's on-accent colour by default", () => new TextRowList().SelectedColor),
            ("P:EmuSen.LunaP.Controls.TextRowList.SelectorColor", "the palette's accent by default", () => new TextRowList().SelectorColor),
            ("P:EmuSen.LunaP.Controls.TextRowList.SelectorOffsetY", "0 by default", () => new TextRowList().SelectorOffsetY),
            ("P:EmuSen.LunaP.Controls.TextRowList.SelectedBackgroundColor", "Transparent by default", () => new TextRowList().SelectedBackgroundColor),
            ("P:EmuSen.LunaP.Controls.TextRowList.SelectedBackgroundCornerRadius", "0 by default", () => new TextRowList().SelectedBackgroundCornerRadius),
            ("P:EmuSen.LunaP.Controls.TextRowList.TextAlignment", "Left by default", () => new TextRowList().TextAlignment),
            ("P:EmuSen.LunaP.Controls.TextRowList.HorizontalMargin", "0 by default", () => new TextRowList().HorizontalMargin),
            ("P:EmuSen.LunaP.Controls.TextRowList.SelectedBackgroundFitsText", "False by default", () => new TextRowList().SelectedBackgroundFitsText),
            ("P:EmuSen.LunaP.Controls.TextRowList.MarkerWidth", "1.5 by default", () => new TextRowList().MarkerWidth),
            ("P:EmuSen.LunaP.Controls.FontText.ScrollDirection", "None by default", () => new FontText().ScrollDirection),
            ("P:EmuSen.LunaP.Controls.TextRowList.LetterCase", "None by default", () => new TextRowList().LetterCase),
        };

        private static readonly Dictionary<string, object?> DrawnValues = new()
        {
            ["P:EmuSen.LunaP.Controls.BadgeStrip.Direction"] = Avalonia.Layout.Orientation.Horizontal,
            ["P:EmuSen.LunaP.Controls.BadgeStrip.Lines"] = 1,
            ["P:EmuSen.LunaP.Controls.BadgeStrip.ItemsPerLine"] = 4,
            ["P:EmuSen.LunaP.Controls.BadgeStrip.ContentHorizontalAlignment"] = Avalonia.Layout.HorizontalAlignment.Left,
            ["P:EmuSen.LunaP.Controls.BadgeStrip.ContentVerticalAlignment"] = Avalonia.Layout.VerticalAlignment.Top,
            ["P:EmuSen.LunaP.Controls.BadgeStrip.Tint"] = Colors.White,
            ["P:EmuSen.LunaP.Controls.ClockLabel.Format"] = "HH:mm",
            ["P:EmuSen.LunaP.Controls.ClockLabel.Live"] = false,
            ["P:EmuSen.LunaP.Controls.DeviceStatusBar.Indicators"] = DeviceIndicators.All,
            ["P:EmuSen.LunaP.Controls.DeviceStatusBar.IconHeight"] = 16.0,
            ["P:EmuSen.LunaP.Controls.DeviceStatusBar.TextScale"] = 1.0,
            ["P:EmuSen.LunaP.Controls.DeviceStatusBar.Color"] = EmuSen.LunaP.Theme.LunaPalette.Text.Color,
            ["P:EmuSen.LunaP.Controls.DeviceStatusBar.BackgroundColor"] = Colors.Transparent,
            ["P:EmuSen.LunaP.Controls.DeviceStatusBar.BackgroundCornerRadius"] = 0.0,
            ["P:EmuSen.LunaP.Controls.DeviceStatusBar.EntrySpacing"] = 6.0,
            ["P:EmuSen.LunaP.Controls.FittedImage.Fit"] = ImageFit.Contain,
            ["P:EmuSen.LunaP.Controls.FittedImage.CropPosition"] = new Avalonia.Point(0.5, 0.5),
            ["P:EmuSen.LunaP.Controls.FittedImage.TileHorizontalAlignment"] = Avalonia.Layout.HorizontalAlignment.Left,
            ["P:EmuSen.LunaP.Controls.FittedImage.TileVerticalAlignment"] = Avalonia.Layout.VerticalAlignment.Top,
            ["P:EmuSen.LunaP.Controls.FittedImage.Tint"] = Colors.White,
            ["P:EmuSen.LunaP.Controls.FittedImage.TintEnd"] = null,
            ["P:EmuSen.LunaP.Controls.FittedImage.TintDirection"] = Avalonia.Layout.Orientation.Horizontal,
            ["P:EmuSen.LunaP.Controls.FittedImage.Saturation"] = 1.0,
            ["P:EmuSen.LunaP.Controls.FittedImage.CornerRadius"] = 0.0,
            ["P:EmuSen.LunaP.Controls.FittedImage.Interpolation"] = Avalonia.Media.Imaging.BitmapInterpolationMode.HighQuality,
            ["P:EmuSen.LunaP.Controls.FontText.FontSize"] = 16.0,
            ["P:EmuSen.LunaP.Controls.FontText.Foreground"] = EmuSen.LunaP.Theme.LunaPalette.Text,
            ["P:EmuSen.LunaP.Controls.FontText.TextAlignment"] = TextAlignment.Left,
            ["P:EmuSen.LunaP.Controls.FontText.TextVerticalAlignment"] = Avalonia.Layout.VerticalAlignment.Top,
            ["P:EmuSen.LunaP.Controls.FontText.LineSpacing"] = 1.2,
            ["P:EmuSen.LunaP.Controls.FontText.LetterCase"] = EmuSen.LunaP.Media.LetterCase.None,
            ["P:EmuSen.LunaP.Controls.FontText.Wrap"] = true,
            ["P:EmuSen.LunaP.Controls.FontText.Ellipsis"] = "\u2026",
            ["P:EmuSen.LunaP.Controls.FontText.Background"] = null,
            ["P:EmuSen.LunaP.Controls.FontText.BackgroundCornerRadius"] = 0.0,
            ["P:EmuSen.LunaP.Controls.HintBar.FontSize"] = 16.0,
            ["P:EmuSen.LunaP.Controls.HintBar.EntryScale"] = 1.0,
            ["P:EmuSen.LunaP.Controls.HintBar.IconColor"] = EmuSen.LunaP.Theme.LunaPalette.Text.Color,
            ["P:EmuSen.LunaP.Controls.HintBar.TextColor"] = EmuSen.LunaP.Theme.LunaPalette.Text.Color,
            ["P:EmuSen.LunaP.Controls.HintBar.BackgroundColor"] = Colors.Transparent,
            ["P:EmuSen.LunaP.Controls.HintBar.BackgroundCornerRadius"] = 0.0,
            ["P:EmuSen.LunaP.Controls.HintBar.EntrySpacing"] = 16.0,
            ["P:EmuSen.LunaP.Controls.HintBar.IconTextSpacing"] = 6.0,
            ["P:EmuSen.LunaP.Controls.HintBar.LetterCase"] = EmuSen.LunaP.Media.LetterCase.None,
            ["P:EmuSen.LunaP.Controls.ImageCarousel.Orientation"] = Avalonia.Layout.Orientation.Horizontal,
            ["P:EmuSen.LunaP.Controls.ImageCarousel.MaxItemCount"] = 3.0,
            ["P:EmuSen.LunaP.Controls.ImageCarousel.ItemScale"] = 1.2,
            ["P:EmuSen.LunaP.Controls.ImageCarousel.Wraps"] = true,
            ["P:EmuSen.LunaP.Controls.ImageCarousel.UnfocusedItemOpacity"] = 0.5,
            ["P:EmuSen.LunaP.Controls.ImageCarousel.UnfocusedItemSaturation"] = 1.0,
            ["P:EmuSen.LunaP.Controls.ImageCarousel.UnfocusedItemDimming"] = 1.0,
            ["P:EmuSen.LunaP.Controls.ImageCarousel.ImageTint"] = Colors.White,
            ["P:EmuSen.LunaP.Controls.ImageCarousel.ImageSaturation"] = 1.0,
            ["P:EmuSen.LunaP.Controls.ImageCarousel.ImageFit"] = ImageFit.Contain,
            ["P:EmuSen.LunaP.Controls.ImageCarousel.ItemVerticalAlignment"] = Avalonia.Layout.VerticalAlignment.Center,
            ["P:EmuSen.LunaP.Controls.ImageCarousel.ItemHorizontalAlignment"] = Avalonia.Layout.HorizontalAlignment.Center,
            ["P:EmuSen.LunaP.Controls.ImageCarousel.Background"] = null,
            ["P:EmuSen.LunaP.Controls.ImageCarousel.FontSize"] = 24.0,
            ["P:EmuSen.LunaP.Controls.ImageCarousel.TextColor"] = EmuSen.LunaP.Theme.LunaPalette.Text.Color,
            ["P:EmuSen.LunaP.Controls.ImageCarousel.TextBackground"] = Colors.Transparent,
            ["P:EmuSen.LunaP.Controls.ImageCarousel.LetterCase"] = EmuSen.LunaP.Media.LetterCase.None,
            ["F:EmuSen.LunaP.Controls.NormalizedCanvas.PositionProperty"] = new Avalonia.Point(0, 0),
            ["F:EmuSen.LunaP.Controls.NormalizedCanvas.SizeProperty"] = new Avalonia.Size(0, 0),
            ["F:EmuSen.LunaP.Controls.NormalizedCanvas.MaxSizeProperty"] = new Avalonia.Size(0, 0),
            ["F:EmuSen.LunaP.Controls.NormalizedCanvas.OriginProperty"] = new Avalonia.Point(0, 0),
            ["F:EmuSen.LunaP.Controls.NormalizedCanvas.RotationProperty"] = 0.0,
            ["F:EmuSen.LunaP.Controls.NormalizedCanvas.RotationOriginProperty"] = new Avalonia.Point(0.5, 0.5),
            ["F:EmuSen.LunaP.Controls.NormalizedCanvas.DepthProperty"] = 0.0,
            ["P:EmuSen.LunaP.Controls.StarRating.StarCount"] = 5,
            ["P:EmuSen.LunaP.Controls.StarRating.Tint"] = Colors.White,
            ["P:EmuSen.LunaP.Controls.TextRowList.FontSize"] = 16.0,
            ["P:EmuSen.LunaP.Controls.TextRowList.LineSpacing"] = 1.5,
            ["P:EmuSen.LunaP.Controls.TextRowList.PrimaryColor"] = EmuSen.LunaP.Theme.LunaPalette.Text.Color,
            ["P:EmuSen.LunaP.Controls.TextRowList.SecondaryColor"] = EmuSen.LunaP.Theme.LunaPalette.Muted.Color,
            ["P:EmuSen.LunaP.Controls.TextRowList.SelectedColor"] = EmuSen.LunaP.Theme.LunaPalette.OnAccent.Color,
            ["P:EmuSen.LunaP.Controls.TextRowList.SelectorColor"] = EmuSen.LunaP.Theme.LunaPalette.Accent.Color,
            ["P:EmuSen.LunaP.Controls.TextRowList.SelectorOffsetY"] = 0.0,
            ["P:EmuSen.LunaP.Controls.TextRowList.SelectedBackgroundColor"] = Colors.Transparent,
            ["P:EmuSen.LunaP.Controls.TextRowList.SelectedBackgroundCornerRadius"] = 0.0,
            ["P:EmuSen.LunaP.Controls.TextRowList.TextAlignment"] = TextAlignment.Left,
            ["P:EmuSen.LunaP.Controls.TextRowList.HorizontalMargin"] = 0.0,
            ["P:EmuSen.LunaP.Controls.TextRowList.SelectedBackgroundFitsText"] = false,
            ["P:EmuSen.LunaP.Controls.TextRowList.MarkerWidth"] = 1.5,
            ["P:EmuSen.LunaP.Controls.FontText.ScrollDirection"] = EmuSen.LunaP.Motion.TextScrollDirection.None,
            ["P:EmuSen.LunaP.Controls.TextRowList.LetterCase"] = EmuSen.LunaP.Media.LetterCase.None,
        };
    }
}
